---
title: "Survey_Data"
format: html
---

## Libraries

```{r}
library(qualtRics)
library(tidyr)
library(knitr)
library(ggplot2)
library(kableExtra)
library(dplyr)
```

## Connect to Qaltrics API

```{r}

qualtrics_api_credentials(api_key = "Zzuvz4t36VkB5akSB8W3Dryg5YgZ9lowoc3JEfEN",
                             base_url = "ucsb.co1.qualtrics.com",
                             install = T,
                          overwrite=TRUE)

```



##  Get all surveys

```{r}
surveys <- all_surveys()

```


## saving survey id

```{r}
i <- which(surveys$name == "Survey for Data Science Training")
id <- surveys$id[i]
```

## List of questions

```{r}
questions <- survey_questions(id)

kable(questions) %>% 
  kable_styling()
```

```{r}
survey_results <- fetch_survey(id)
```

# question 2

```{r}
q2 <- survey_results %>% 
    select(Q2) %>% 
    group_by(Q2) %>% 
    summarise(n = n())  
  
kable(q2, col.names = c("How long have you been programming?",
                        "Number of responses")) %>%
    kable_styling()
```


# question 3

```{r}
q3 <- survey_results %>% 
    select(Q3) %>% 
    group_by(Q3) %>% 
    summarise(n = n())

ggplot(data = q3, 
       mapping = aes(x = Q3, y = n)) +
    geom_col() +
    labs(x = "What language do you currently use most frequently?", y = "Number of reponses") +
    theme_minimal()
```
Look at other part of question 3 (Free Text)

```{r}
q3_text <- survey_results %>% 
  select(Q3_7_TEXT) %>% 
  drop_na()

kable(q3_text, col.names = "Other Responses to 'What language do you currently use'") %>% 
  kable_styling()
```





